language: node_js
services:
  - docker
node_js:
  - 9.9.0
git:
  depth: 10
cache:
  directories:
    - node_modules
    - server/node_modules
env:
  global:
    - NODE_ENV=production ESLINT_BEFORE_BUILD=false
  matrix:
    - SCRIPT="lint"
    - SCRIPT="test"
    - SCRIPT="build"
install:
  - npm install
  - cd server && npm install --dev && cd ..
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export BRANCH_OR_PR="$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo "PR-$TRAVIS_PULL_REQUEST"; fi)"
  - export SOURCE_URL="$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "https://github.com/"$REPO_OWNER"/"$REPO_NAME"/commit/"$TRAVIS_COMMIT""; else echo "https://github.com/"$REPO_OWNER"/"$REPO_NAME"/pull/"$TRAVIS_PULL_REQUEST""; fi)"
script: (eval "$SCRIPT")
# TODO After getting the build right:
#deploy:
#  provider: script
#  script: ./.travis/deploy.sh
#  on:
#    all_branches: true
after_failure:
  - chmod +x .travis/discord-hook/fail.sh
  - ./.travis/discord-hook/fail.sh
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
