language: node_js
services:
  - docker
node_js:
  - 9.9.0
git:
  depth: 10
cache:
  directories:
    - node_modules
    - server/node_modules
env:
  global:
    - NODE_ENV=production ESLINT_BEFORE_BUILD=false
  matrix:
    - SCRIPT="lint"
    - SCRIPT="test"
    - SCRIPT="build"
install:
  - npm install
  - cd server && npm install --dev && cd ..
script:
  - (eval "chmod +x .travis/$SCRIPT.sh")
  - (eval "./.travis/$SCRIPT.sh")
# TODO After getting the build right:
#deploy:
#  provider: script
#  script: ./.travis/deploy.sh
#  on:
#    all_branches: true
#after_failure:
#  - chmod +x .travis/discord-hook/fail.sh
#  - ./.travis/discord-hook/fail.sh
#notifications:
#  webhooks: https://www.travisbuddy.com/
#  on_success: never
